// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Usuarios.Domain.Entities;

public partial class Huespede
{
    public int HuespedId { get; set; }

    public string UsuarioId { get; set; }

    public string NombreCompleto { get; set; }

    public string TipoDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public string Nacionalidad { get; set; }

    public DateTime FechaNacimiento { get; set; }

    public string ContactoEmergencia { get; set; }

    public string TelefonoEmergencia { get; set; }

    public bool EsVip { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string PreferenciasAlimentarias { get; set; }

    public string NotasEspeciales { get; set; }
}