// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Usuarios.Domain.Entities;

public partial class PermisosPersonal
{
    public int PermisoId { get; set; }

    public int PersonalId { get; set; }

    public int? HabitacionId { get; set; }

    public string TipoPermiso { get; set; }

    public DateTime FechaOtorgamiento { get; set; }

    public DateTime? FechaExpiracion { get; set; }

    public bool EsTemporal { get; set; }

    public string OtorgadoPor { get; set; }

    public bool EstaActivo { get; set; }

    public string Justificacion { get; set; }

    public virtual Personal Personal { get; set; }
}