// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Usuarios.Domain.Entities;

public partial class Personal
{
    public int PersonalId { get; set; }

    public string UsuarioId { get; set; }

    public int HotelId { get; set; }

    public string NombreCompleto { get; set; }

    public string Puesto { get; set; }

    public string Departamento { get; set; }

    public string NumeroEmpleado { get; set; }

    public DateTime FechaContratacion { get; set; }

    public bool EstaActivo { get; set; }

    public string Turno { get; set; }

    public int? Supervisor { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<Personal> InverseSupervisorNavigation { get; set; } = new List<Personal>();

    public virtual ICollection<PermisosPersonal> PermisosPersonals { get; set; } = new List<PermisosPersonal>();

    public virtual Personal SupervisorNavigation { get; set; }
}